"""
Pydantic data models for Robot Agent inter-node communication.

All models are serialized to JSON via model_dump_json() / model_validate_json()
(Pydantic v2 built-ins — no wrapper methods needed).
"""

import time
import uuid
from typing import Optional

from pydantic import BaseModel, Field


class Object(BaseModel):
    """Single object properties which the detector can infer from an image."""

    id: int = Field(..., description="Unique object ID")
    label: str = Field(..., description="Object class label")
    bbox: list[int] = Field(..., description="Bounding box [x1, y1, x2, y2] in pixels")
    confidence: float = Field(..., description="Detection confidence 0-100")


class ObjectWithDepth(Object):
    """Detected object enriched with depth and 3D world position."""

    depth_meters: Optional[float] = Field(
        default=None, description="Distance to object in metres (None if invalid)"
    )
    world_pos: list[float] = Field(
        default_factory=list,
        description="World position [x, y, z] in local ENU frame (metres)",
    )
    depth_valid: bool = Field(default=False, description="True when depth measurement is reliable")


class SceneDescription(BaseModel):
    """Complete scene description with detected objects and 3D positions."""

    summary: str = Field(..., description="Concise scene description")
    objects: list[ObjectWithDepth] = Field(..., description="Detected objects with 3D positions")
    camera_pos: Optional[list[float]] = Field(
        default=None, description="Camera position [x, y, z] in local frame"
    )
    img_res: Optional[list[int]] = Field(
        default=None, description="Image resolution [width, height] in pixels"
    )

class WorldModel(BaseModel):
    """World model — environment observations independent of vehicle type."""

    detections: list[dict] = Field(
        default_factory=list, description="Detected objects with depth and world positions"
    )
    lidar_ranges: Optional[dict[str, float]] = Field(
        default=None, description="LiDAR sector distances in metres; None if no LiDAR sensor"
    )


class RobotState(BaseModel):
    """Robot state — odometry, orientation, and flight/operational status."""

    position_x: float = Field(default=0.0, description="Position X in local ENU frame (metres)")
    position_y: float = Field(default=0.0, description="Position Y in local ENU frame (metres)")
    position_z: float = Field(default=0.0, description="Position Z in local ENU frame (metres)")

    velocity_x: Optional[float] = Field(default=None, description="Velocity X in local ENU frame (m/s)")
    velocity_y: Optional[float] = Field(default=None, description="Velocity Y in local ENU frame (m/s)")
    velocity_z: Optional[float] = Field(default=None, description="Velocity Z in local ENU frame (m/s)")

    orientation_roll: float = Field(default=0.0, description="Roll angle in degrees")
    orientation_pitch: float = Field(default=0.0, description="Pitch angle in degrees")
    orientation_yaw: float = Field(default=0.0, description="Yaw angle in degrees")

    flight_mode: Optional[str] = Field(default=None, description="Current flight/operational mode")
    armed: bool = Field(default=False, description="True when vehicle is armed")
    connected: bool = Field(default=False, description="True when vehicle is connected")


class ToolCall(BaseModel):
    """A single tool invocation in a mission plan."""

    tool: str
    args: dict = Field(default_factory=dict)
    reasoning: str = ""


class MissionPlan(BaseModel):
    """Mission plan generated by the agent."""

    timestamp: float = Field(
        default_factory=time.time, description="Plan creation timestamp (seconds)"
    )
    mission_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()), description="Unique mission identifier"
    )
    steps: list[ToolCall] = Field(..., description="Ordered tool calls to execute")
    reasoning: str = Field(..., description="Step-by-step thinking that led to this plan")
    user_query: Optional[str] = Field(default=None, description="Original user query")
    safety_checks: list[str] = Field(..., description="Safety constraints to enforce")


class ExecutionStatus(BaseModel):
    """Execution status of a mission plan."""

    timestamp: float
    mission_id: str
    current_waypoint_index: int
    total_waypoints: int
    position_error: float = Field(..., description="Current distance from target (metres)")
    message: str
    state: str = Field(
        ...,
        description="One of: idle, executing, paused, completed, aborted, failed",
    )
    reasoning: str = Field(default="", description="Planner reasoning for the current mission")
